# Generated by Django 2.1.1 on 2023-05-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HiredApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ofuserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofuserId_Rating_User', to='HiredApp.User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='touseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touseId_Rating_User', to='HiredApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creditcard',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='taskId',
            field=models.IntegerField(null=True),
        ),
    ]
